services:

  postgresql:
    image: postgres:15.12-bookworm
    restart: always
    volumes:
      - /volume1/docker/keycloak/data/database:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - default

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.5
    labels:
      traefik.enable: true
      traefik.docker.network: shared
      traefik.http.routers.keycloak.entrypoints: websecure
      traefik.http.routers.keycloak.rule: PathPrefix(`/keycloak`)
      traefik.http.services.keycloak.loadbalancer.server.port: 8080
    depends_on:
      - postgresql
    restart: always
    command: start-dev
    environment:
      TZ: Asia/Tokyo
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Keycloak12345
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_PROXY_HEADERS: xforwarded
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL_HOST: postgresql
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
    extra_hosts:
      - synology-nas.local:host-gateway
    networks:
      - default
      - shared
    deploy:
      resources:
        limits:
          cpus: mid
          memory: 1g

networks:
  shared:
    external: true
